### ISSUE TITLE
Put Nukomeet staff photos on Google Drive

### ISSUE THREAD

**Issue by truepl** [nukomeet/nukomeet.com#198]
@myviridis

**Comment by myviridis** [comment]
All pictures are here: https://drive.google.com/open?id=0B7TfKu93uh00fmxqbWhwMWp2eFJPb3dmMDBYNzZSTkQ2djZ0WUtxc1gzaU9oaFZWZFZzU0k

*Kasia Popek*

Communications Manager at Nukomeet


___


You can contact me at

mail *kasia@nukomeet.com*

mobile *+48 609 160 095*


Visit our website *www.nukomeet.com*




On Wed, Jul 22, 2015, at 12:35 PM, Paweł Wodkowski wrote:
> @myviridis[1]


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/myviridis
  2. https://github.com/nukomeet/nukomeet.com/issues/198
