### ISSUE TITLE
Menu problems - 404

### ISSUE THREAD

**Issue by agnieszkabukowska** [nukomeet/nukomeet.com#206]
When I click on Workshops in the menu, I go to 404 error page.
https://nukomeet.com/workshops/react/workshops.html

I think there is a problem with links because this one works: https://nukomeet.com/workshops.html

I have the same problem with Career, the links https://nukomeet.com/company/career.html is not working, should be remplaced.

**Comment by pawelwodkowski** [comment]
Done.
