### ISSUE TITLE
RWD issues

### ISSUE THREAD

**Issue by agnieszkabukowska** [nukomeet/nukomeet.com#208]
GENERAL
- [x] footer - SUBSCRIBE button is not aligned
- [x] review big white empty spaces, we are loosing place here, ex:

HOME
ok

COMPANY
- [x] images are overpassing the text
- [x] photos of the team are overpassing each other, sometimes we have 2 people in the row, sometimes 

SERVICES
- [x] images are overpassing the text

WORK
- [x] problem with images

BLOG
- [ ] single post - I don't know if it's ok that the text is on the image?
  Probably yes, just asking ;)
  ![zrzut ekranu 2015-12-23 o 10 05 47](https://cloud.githubusercontent.com/assets/11835317/11973662/cf1dec48-a95c-11e5-87a3-261155426051.png)

CAREER
- [x] change the display of elements (one after another vertically?)
  ![zrzut ekranu 2015-12-23 o 10 10 24](https://cloud.githubusercontent.com/assets/11835317/11973739/b22babe2-a95d-11e5-98d0-70c2995c7ded.png)

**Comment by pawelwodkowski** [comment]
@agnieszkabukowska This newsletter should be right aligned.
